### ISSUE TITLE
OneDrive sign-in problems

### ISSUE THREAD

**Issue by MaxTheWhale** [MaxTheWhale/firefox-extensions-ecosystem#1]
This issue occurs when authenticating with OneDrive using the library. It can easily be recreated by running the integration test. I'm using the latest Firefox Nightly build.

When the sign-in popup has appeared and credentials have been provided, the expected behaviour is authentication should happen reasonably quickly and be successful. The actual behaviour is that the sign-in screen hangs for a long time, before eventually either timing out or completing successfully, seemingly randomly.

The amount of time that the page hangs for seems to vary on different devices. On my desktop PC (Windows), it always pauses for about 45 seconds. On my laptop (Linux), the pause lasts for about 180 seconds. The length of the pause seems to be consistent each time, however.

For the first half of time, the page is waiting for login.live.com.
![page1](https://user-images.githubusercontent.com/34164145/53763884-c4a1e580-3ec3-11e9-816c-c9b27ac4d9a8.png)

For the second half of time, the page is connecting to extensions.allizom.org.
![page2](https://user-images.githubusercontent.com/34164145/53764026-177b9d00-3ec4-11e9-9b6b-9b8b72e8c581.png)

Sometimes, the authentication will time-out and go to this error page. Notice that in the address bar, the access token has been successfully returned in the URL params, the redirect just fails for some reason.
![error](https://user-images.githubusercontent.com/34164145/53764034-1b0f2400-3ec4-11e9-9357-314a73febf08.png)

These are the network requests that appear in the debug tools. The long pause can be clearly seen on the last request, and it breaks it down into 50% blocked and 50% waiting on DNS.
![requests](https://user-images.githubusercontent.com/34164145/53764038-1c405100-3ec4-11e9-884f-9cd086cd7df1.png)

**Comment by rpl** [comment]
The following bugzilla issue may be related to the issue experienced on OneDrive sign-in:
- [Bug 1528562 - browser.identity.launchWebAuthFlow hangs after authentication](https://bugzilla.mozilla.org/show_bug.cgi?id=1528562)

**Comment by MaxTheWhale** [comment]
After applying the fix suggested in the thread (changing from extensions.allizom.org to extensions.mozilla.org for the redirect URL), the delay has been eliminated, however the sign-in still fails some of the time. I suspect it may be some other issue, as it was not mentioned in the above bugzilla thread.

**Comment by MaxTheWhale** [comment]
The inconsistent sign-in was caused by a bug in our code where launchWebAuthFlow was being called twice in succession, causing the second one to fail. This has now been fixed as of the latest commit so the issue can be closed.
